# Mini Motorways 自动化配置文件

# 游戏窗口配置
game:
  window_title: "Mini Motorways"  # 游戏窗口标题
  expected_resolution: [1920, 1080]  # 期望的游戏分辨率
  screenshot_region: null  # 截图区域，null表示全窗口

# 截图配置
screenshot:
  save_raw: true  # 是否保存原始截图
  save_marked: true  # 是否保存标记版截图
  format: "png"  # 图片格式
  quality: 95  # 图片质量

# 日志配置
logging:
  level: "INFO"  # 日志级别: DEBUG, INFO, WARNING, ERROR
  max_screenshots_per_session: 1000  # 单次会话最大截图数量
  cleanup_old_logs: true  # 是否清理旧日志
  keep_days: 7  # 保留日志天数

# 远程服务器配置
remote_server:
  enabled: false  # 是否启用远程决策
  url: "http://localhost:8000/api/decision"  # 服务器API地址
  timeout: 5  # 请求超时时间（秒）
  retry_times: 3  # 重试次数

# 图像识别配置
recognition:
  confidence_threshold: 0.8  # 识别置信度阈值
  template_matching_threshold: 0.7  # 模板匹配阈值
  ocr_languages: ["en", "ch_sim"]  # OCR支持的语言

# 操作配置
automation:
  click_delay: 0.1  # 点击操作间隔（秒）
  drag_speed: 1.0  # 拖拽速度
  screenshot_interval: 0.5  # 截图间隔（秒）
  max_operation_retry: 3  # 操作重试次数 